app/songs/models.py
from .. import db

class categorysong(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    musicType = db.Column(db.String(50), nullable=False)
    songs = db.relationship('Songs', backref='category', lazy=True)


class Songs(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    songWriter = db.Column(db.String(100), nullable=False)
    songName = db.Column(db.String(120), nullable=False)
    songDescription = db.Column(db.Text, nullable=True)
    songDuration = db.Column(db.Text, nullable=True)
    songLink = db.Column(db.String(250), nullable=False)
    songCategory = db.Column(db.Integer, db.ForeignKey('categorysong.id'), nullable=True)
    songYear = db.Column(db.Integer, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.id}', '{self.songWriter}')"

app/songs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SubmitField, IntegerField
from wtforms.validators import Length, DataRequired, InputRequired
from flask_wtf.file import FileField, FileAllowed

class AddSongsForm(FlaskForm):
    songWriter = StringField('Автори', validators=[InputRequired(), Length(min=5, max=100)])
    songName = StringField('Назва', validators=[InputRequired(), Length(min=5, max=120)])
    songDescription = TextAreaField('Опис', validators=[Length(max=2500)])
    songDuration = StringField('Тривалість', validators=[InputRequired(), Length(min=3, max=15)])
    songLink = StringField('Посилання на кліп', validators=[InputRequired(), Length(min=2, max=250)])
    songCategory = SelectField(u'Тип музики', coerce=int)
    songYear = IntegerField('Рік виходу', validators=[DataRequired()])
    submit = SubmitField('')

class CategoryForm(FlaskForm):
    name = StringField("Ім'я категорії", validators=[DataRequired(), Length(min=0, max=60)])
    submit = SubmitField('')

app/songs/__init__.py
from flask import Blueprint

songs_blueprint = Blueprint('songs', __name__, template_folder="templates/songs")

from . import views

app/songs/views.py
from flask import url_for, render_template, flash, request, redirect, abort, current_app
from .forms import AddSongsForm, CategoryForm
from . import songs_blueprint
from .models import categorysong, Songs
from .getFunctions import getFooterData
from .. import db
from flask_login import current_user, login_required

@songs_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def view_songs():
    songs = Songs.query.order_by(Songs.songWriter).all()
    return render_template('view_songs.html', songs=songs, data=getFooterData())


@songs_blueprint.route('/addsongs', methods=['GET', 'POST'])
@login_required
def add_song():
    form = AddSongsForm()
    form.songCategory.choices = [(category.id, category.musicType) for category in categorysong.query.all()]
    if form.validate_on_submit():
        Song = Songs(songWriter=form.songWriter.data,
                     songName=form.songName.data,
                     songDescription=form.songDescription.data,
                     songDuration=form.songDuration.data,
                     songLink=form.songLink.data,
                     songCategory=form.songCategory.data,
                     songYear=form.songYear.data,
                     user_id=current_user.id)

        db.session.add(Song)
        db.session.commit()

        return redirect(url_for('songs.view_songs'))
    return render_template('songs_add.html', form=form, data=getFooterData())


@songs_blueprint.route('/<id>', methods=['GET', 'POST'])
def detail_song(id):
    songs = Songs.query.get_or_404(id)
    return render_template('songs_detail.html', pk=songs, data=getFooterData())


@songs_blueprint.route('/delete/<id>', methods=['GET', 'POST'])
def delete_song(id):
    songs = Songs.query.get_or_404(id)
    if current_user.id == songs.user_id:
        db.session.delete(songs)
        db.session.commit()
        return redirect(url_for('songs.view_songs'))

    flash('Це не ваш запис!', category='error')
    return redirect(url_for('songs.detail_songs', pk=id))


@songs_blueprint.route('/edit/<id>', methods=['GET', 'POST'])
def edit_song(id):
    songs = Songs.query.get_or_404(id)
    if current_user.id != songs.user_id:
        flash('Це не ваш запис!', category='error')
        return redirect(url_for('songs.detail_songs', pk=songs))

    form = AddSongsForm()
    form.songCategory.choices = [(category.id, category.musicType) for category in categorysong.query.all()]

    if form.validate_on_submit():
        songs.songWriter = form.songWriter.data
        songs.songName = form.songName.data
        songs.songDescription = form.songDescription.data
        songs.songDuration = form.songDuration.data
        songs.songLink = form.songLink.data
        songs.songCategory = form.songCategory.data
        songs.songYear = form.songYear.data

        db.session.add(songs)
        db.session.commit()

        flash('Пісня успішно змінена!', category='success')
        return redirect(url_for('songs.detail_song', id=id))

    form.songWriter.data = songs.songWriter
    form.songName.data = songs.songName
    form.songDescription.data = songs.songDescription
    form.songDuration.data = songs.songDuration
    form.songLink.data = songs.songLink
    form.songCategory.data = songs.songCategory
    form.songYear.data = songs.songYear

    return render_template('songs_add.html', form=form, data=getFooterData())


@songs_blueprint.route('/catacrcrud', methods=['GET', 'POST'])
def category_crud():
    form = CategoryForm()

    if form.validate_on_submit():
        category = categorysong(musicType=form.name.data)

        db.session.add(category)
        db.session.commit()
        flash('Категорія добавленна успішно!', category='success')
        return redirect(url_for('.category_crud'))

    categories = categorysong.query.all()
    return render_template('category_crud.html', categories=categories, form=form, data=getFooterData())


@songs_blueprint.route('/update_category/<id>', methods=['GET', 'POST'])
def update_category(id):
    category = categorysong.query.get_or_404(id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.musicType = form.name.data

        db.session.add(category)
        db.session.commit()
        flash('Категорія відредагована успішно!', category='success')
        return redirect(url_for('.category_crud'))

    form.name.data = category.musicType
    categories = categorysong.query.all()
    return render_template('category_crud.html', categories=categories, form=form, data=getFooterData())


@songs_blueprint.route('/delete_category/<id>', methods=['GET'])
@login_required
def delete_category(id):
    category = categorysong.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()

    flash('Category delete', category='success')
    return redirect(url_for('.category_crud'))

app/songs/templates/songs/category_crud.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}
    <title>Створити пост</title>

    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{cat}}">{{msg}}</div>
    {% endfor %}

    <div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Керування <b>Категоріями "Музика"</b>
                    <button type="button" class="btn btn-success float-right" data-bs-toggle="modal" data-bs-target="#mymodal">
                        Додати нову категорію
                    </button>
                </h2>
                <table class="table table-hover table-dark">
                    <tr>
                        <th>id</th>
                        <th>Тип музики</th>
                        <th>Дії</th>
                    </tr>

                    {% for category in categories %}
                    <tr>
                        <td>{{category.id}}</td>
                        <td>{{category.musicType}}</td>
                        <td>
                            <a href="{{ url_for('songs.update_category', id=category.id) }}"
                               class="btn btn-warning btn-xs" data-bs-toggle="modal"
                               data-bs-target="#modaledit{{category.id}}">Редагувати</a>
                            <a href="{{ url_for('songs.delete_category', id=category.id) }}"
                               class="btn btn-danger btn-xs"
                               onclick="return confirm('Ви впевнені, що бажаєте видалити даний запис?')">Видалити</a>
                        </td>

                    </tr>

                    <div id="modaledit{{category.id}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Оновлення даних</h4>
                                </div>
                                <div class="modal-body">
                                    <form action="{{url_for('songs.update_category', id=category.id)}}" method="POST">
                                        {{ form.csrf_token }}
                                        <div class="form-group">
                                            {{ render_field(form.name, class="form-control", value=category.update_category) }}
                                        </div>
                                        <div class="form-group">
                                            {{ render_field(form.submit, class="btn btn-primary", value="Змінити") }}
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </table>
            </div>

            <div id="mymodal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Додати категорію пісні</h4>
                        </div>
                        <div class="modal-body">
                            <form action="{{url_for('songs.category_crud')}}" method="POST">
                                {{ form.csrf_token }}
                                <div class="form-group">
                                    {{ render_field(form.name, class="form-control") }}
                                </div>
                                <div class="form-group">
                                    {{ render_field(form.submit, class="btn btn-primary", value="Додати") }}
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

app/songs/templates/songs/songs_add.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}
    <title>Додати пісню</title>

    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{cat}}">{{msg}}</div>
    {% endfor %}

<form method="POST" enctype="multipart/form-data" id="add-new-song-area">
     <h2 align="center">Додайте пісню</h2>
        <hr>
    {{ form.csrf_token }}
    <div class="block-form-post">
        <div class="form-post">
            <div class="form-item">{{ render_field(form.songWriter, id="add-song-songWriter") }}</div>
            <div class="form-item">{{ render_field(form.songName, id="add-song-songName") }}</div>
            <div class="form-item">{{ render_field(form.songDescription, id="add-song-songDescription") }}</div>
            <div class="form-item">{{ render_field(form.songDuration, id="add-song-songDuration") }}</div>
            <div class="form-item">{{ render_field(form.songLink, id="add-song-songLink") }}</div>
            <div class="form-item">{{ render_field(form.songCategory, id="add-song-songCategory") }}</div>
            <div class="form-item">{{ render_field(form.songYear, id="add-song-songYear") }}</div>
            <div class="form-item">{{ render_field(form.submit, value="Зберегти", id="add-song-submit")  }}</div>
        </div>
    </div>

</form>

{% endblock %}

app/songs/templates/songs/songs_detail.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}
    <title>Інформація про пісню</title>

    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{cat}}">{{msg}}</div>
    {% endfor %}

<div id="detail-song-area">
    <div>
        <h1>{{ pk.songName }}</h1>
        <hr>
        <p style="text-align: left; display: inline-block;" >Автор пісні: <p id="span-song-info-songWriter">{{ pk.songWriter }}</p></p>
        <p style="text-align: left; display: inline-block;" >Опис: <p id="span-song-info-songDescription">{{ pk.songDescription }}</p></p>
        <p style="text-align: left; display: inline-block;" >Тривалість: <p id="span-song-info-songDuration">{{ pk.songDuration }}</p></p>
        <p style="text-align: left; display: inline-block;" >Ссилка на кліп:</p>
        <a href="{{ pk.songLink }}" id="span-song-info-songLink">{{ pk.songName }} - {{ pk.songWriter }}</a>
        <p style="text-align: left; display: inline-block;" >Тип музики: <p id="span-song-info-musicType">{{ pk.category.musicType }}</p></p>
        <p style="text-align: left; display: inline-block;" >Рік виходу: <p id="span-song-info-songYear">{{ pk.songYear }}</p></p>

        <hr>
    </div>
    <div class="buttons">
        {% if current_user.id == pk.user_id %}
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Видалити</button>
        <a href="{{ url_for('songs.edit_song', id=pk.id) }}">
            <button class="btn btn-primary">Редагувати</button>
        </a>
        {% endif %}
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Видалити пісню?</h5>
                <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Ви дійсно бажаєте видалити дану пісню?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                <form action="{{ url_for('songs.delete_song', id=pk.id) }}" method="POST"> <!-- delete !-->
                    <button class="btn btn-danger" type="submit">Видалити</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/songs/templates/songs/view_songs.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}
    <title>Додати пісню</title>

    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{cat}}">{{msg}}</div>
    {% endfor %}

    <div id="main-div-song">
            {% for song in songs %}
                    <div id="song-container">
                        <h1><a href="{{ url_for('songs.detail_song', id=song.id) }}">{{ song.songName }}</a></h1>
                        <hr>
                        <p id="span-song-author">Автор: {{ song.songWriter }}</p>
                        <p id="span-song-type">Тип музики: {{ song.category.musicType }}</p>
                        <hr>
                        <p>
                            <span id="span-song-year">Рік виходу: {{ song.songYear }}</span>
                            <span id="span-song-duration">Тривалість: {{ song.songDuration }}</span>
                        </p>
                    </div>
            {% endfor %}
    </div>
{% endblock %}