app/posts/models.py
import enum

from .. import db
# from sqlalchemy.types import Enum


post_tags_identifier = db.Table(
    'post_tags_identifier',
    db.Column('tags', db.Integer, db.ForeignKey('tag.id')),
    db.Column('post_id', db.Integer, db.ForeignKey('post.id'))
)

class PostType(enum.Enum):
    News = 'News'
    Publication = 'Publication'
    Other = 'Other'

class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)
    posts = db.relationship("Post", back_populates="category")


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), nullable=False)
    description = db.Column(db.Text, nullable=True)
    image = db.Column(db.String(20), nullable=False, default='default_post.png')
    created = db.Column(db.DateTime, default=db.func.now())
    is_enabled = db.Column(db.Boolean, default=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
    tags = db.relationship("Tag", secondary=post_tags_identifier)
    category = db.relationship("Category", back_populates="posts")

db.create_all()

app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SubmitField, SelectMultipleField
from wtforms.validators import Length, DataRequired, InputRequired
from flask_wtf.file import FileField, FileAllowed


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[InputRequired(), Length(min=2, max=60)])
    description = TextAreaField('Опис', validators=[Length(max=500)])
    image = FileField('Завантажити фото', validators=[FileAllowed(['jpg', 'png'])])
    category = SelectField('Категорія', validators=[InputRequired()])
    tags = SelectMultipleField("Теги", validators=[InputRequired()], coerce=int)
    submit = SubmitField('')

class CategoryForm(FlaskForm):
    name = StringField('Назва', validators=[InputRequired(), Length(min=2, max=50)])
    submit = SubmitField('')

app/posts/__init__.py
from flask import Blueprint

post_blueprint = Blueprint('post', __name__, template_folder="templates")

from . import views

app/posts/views.py
from .models import Post, Tag, Category
from .forms import PostForm, CategoryForm
from flask import url_for, render_template, flash, request, redirect, abort, current_app
from .. import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from .getFunction import getFooterData, save_picture
from . import post_blueprint


@post_blueprint.route('/', methods=['GET', 'POST'])
def index():
    posts = Post.query.order_by(Post.created.desc())
    image = url_for('static', filename='posts_pics/')
    return render_template('index.html', posts=posts, image=image, data=getFooterData())


@post_blueprint.route('/<pk>', methods=['GET', 'POST'])
def view_detail(pk):
    get_post = Post.query.get_or_404(pk)
    return render_template('detail_post.html', pk=get_post, data=getFooterData())


@post_blueprint.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = PostForm()
    categories = Category.query.all()
    tags = Tag.query.all()

    form.category.choices = [(category.id, category.name)
                             for category in categories]
    form.tags.choices = [(tag.id, tag.name) for tag in tags]

    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            image = picture_file
        else:
            image = 'postdefault.jpg'

        tags = [Tag.query.get(tag_id) for tag_id in form.tags.data]
        post = Post(title=form.title.data,
                    description=form.description.data,
                    image=image,
                    user_id=current_user.id,
                    category_id=form.category.data,
                    tags=tags)

        db.session.add(post)
        db.session.commit()
        return redirect(url_for('post.index'))
    return render_template('create_post.html', form=form, data=getFooterData())


@post_blueprint.route('/delete/<pk>', methods=['GET', 'POST'])
def delete_post(pk):
    get_post = Post.query.get_or_404(pk)
    if current_user.id == get_post.user_id:
        db.session.delete(get_post)
        db.session.commit()
        return redirect(url_for('post.index'))
    flash('Ця дія заборонена! Пост не є ваш!', category='error')
    return redirect(url_for('post.view_detail', pk=pk))


@post_blueprint.route('/update/<pk>', methods=['GET', 'POST'])
def update_post(pk):
    post = Post.query.get_or_404(pk)
    if current_user.id != post.user_id:
        flash('Ця дія заборонена! Пост не є ваш!', category='error')
        return redirect(url_for('post.view_detail', pk=pk))
    form = PostForm()
    categories = Category.query.all()
    tags = Tag.query.all()

    form.category.choices = [(category.id, category.name)
                             for category in categories]
    form.tags.choices = [(tag.id, tag.name) for tag in tags]
    if form.validate_on_submit():
        if form.image.data:
            image = save_picture(form.image.data)
            post.image = image

        post.title = form.title.data
        post.description = form.description.data
        post.category_id = form.category.data
        post.tags = [Tag.query.get(tag_id) for tag_id in form.tags.data]

        db.session.commit()
        #db.session.add(get_post)
        flash('Ви успішно редагували пост!', category='success')
        return redirect(url_for('post.view_detail', pk=pk))

    form.category.data = post.category_id
    form.category.default = post.category_id
    form.tags.data = [tag.id for tag in post.tags]
    form.process()
    form.title.data = post.title
    form.description.data = post.description

    return render_template('update_post.html', form=form, data=getFooterData())

@post_blueprint.route('/categories', methods=['GET', 'POST'])
def categories():
    form = CategoryForm()
    if form.name.data:
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        form.name.data = ''
        flash('Категорія ' + category.name + ' додана!', category='success')
    categories = Category.query.all()
    return render_template('categories.html', categories=categories, form=form, data=getFooterData())

@post_blueprint.route('/update_category/<id>', methods=['GET', 'POST'])
def update_post_category(id):
    category = Category.query.get_or_404(id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data

        db.session.add(category)
        db.session.commit()
        flash('Категорія відредагована успішно!', category='success')
        return redirect(url_for('.categories'))

    form.name.data = category.name
    categories = Category.query.all()
    return render_template('categories.html', categories=categories, form=form, data=getFooterData())

@post_blueprint.route('/delete_category/<id>', methods=['GET'])
@login_required
def delete_post_category(id):
    category = Category.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()

    flash('Категорія видалена успішно', category='success')
    return redirect(url_for('.categories'))



def get_category_name(id):
    return Category.query.get(id).name

current_app.jinja_env.globals.update(get_category_name=get_category_name)

app/posts/templates/categories.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}

    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{cat}}">{{msg}}</div>
    {% endfor %}

    <div class="container">
        <div class="row">
            <div class="col md-12">
                <div class="jumbotron p-3">
                    <h2>Керування <b>Категоріями "Пост"</b>
                        <button type="button" class="btn btn-success float-right" data-bs-toggle="modal" data-bs-target="#mymodal">
                            Додати нову категорію
                        </button>
                    </h2>
                    <table class="table table-hover table-dark">
                        <tr>
                            <th>id</th>
                            <th>Назва категорії</th>
                            <th>Дії</th>
                        </tr>

                        {% for cat in categories %}
                        <tr>
                            <td>{{cat.id}}</td>
                            <td>{{cat.name}}</td>
                            <td>
                                <a href="{{ url_for('post.update_post_category', id=cat.id) }}"
                                   class="btn btn-warning btn-xs" data-bs-toggle="modal"
                                   data-bs-target="#modaledit{{cat.id}}">Редагувати</a>
                                <a href="{{ url_for('post.delete_post_category', id=cat.id) }}"
                                   class="btn btn-danger btn-xs"
                                   onclick="return confirm('Ви впевнені, що бажаєте видалити даний запис?')">Видалити</a>
                            </td>

                        </tr>

                        <div id="modaledit{{cat.id}}" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Оновлення даних</h4>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{url_for('post.update_post_category', id=cat.id)}}" method="POST">
                                            {{ form.csrf_token }}
                                            <div class="form-group">
                                                {{ render_field(form.name, class="form-control", value=cat.update_category) }}
                                            </div>
                                            <div class="form-group">
                                                {{ render_field(form.submit, class="btn btn-primary", value="Змінити") }}
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </table>
                </div>

                <div id="mymodal" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Додати категорію для поста</h4>
                            </div>
                            <div class="modal-body">
                                <form action="{{url_for('post.categories')}}" method="POST">
                                    {{ form.csrf_token }}
                                    <div class="form-group">
                                        {{ render_field(form.name, class="form-control") }}
                                    </div>
                                    <div class="form-group">
                                        {{ render_field(form.submit, class="btn btn-primary", value="Додати") }}
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>




{% endblock %}

app/posts/templates/create_post.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}
    <title>Створити пост</title>

    <form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div id="create-post">
        <div>
            <p>{{ render_field(form.title, id="create-post-title") }}</p>
            <p>{{ render_field(form.description, id="create-post-content") }}</p>
            <p>{{ render_field(form.image, id="create-post-picture") }}</p>
            <p>{{ render_field(form.category, id="create-category-type") }}</p>
            <p>{{ render_field(form.tags, id="create-tags-type") }}</p>
            <p>{{ render_field(form.submit, value='Зберегти', id="create-post-submit_btn") }}</p>
        </div>
    </div>

</form>

{% endblock %}

app/posts/templates/detail_post.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}
    <title>Новини</title>

    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{cat}}">{{msg}}</div>
    {% endfor %}

    <div id="detail-post">
        <div class="item-post">
            <div class="post_tags">
                Теги:
                {% for tag in pk.tags %}
                    {{ tag.name }},
                {% endfor %}
            </div>
            <br>
            <span class="post_type">
                Категорія: {{ get_category_name(pk.category_id) }}
            </span>
            <span class="post_date">
                {{ pk.created }}
            </span>

            <img src="/static/posts_pics/{{ pk.image }}" width="400px">
            <p id="title-post">{{ pk.title }}</p>
            <hr>
            <p id="content-post">{{ pk.description  }}</p>
            <hr>


            <hr>
        </div>
        <div>
            {% if current_user.id == pk.user_id %}
                <a href="{{ url_for('post.delete_post', pk=pk.id) }}"><button id="delete-post-btn">Видалити</button></a>
                <a href="{{ url_for('post.update_post', pk=pk.id) }}"><button id="edit-post-btn">Редагувати</button></a>
            {% endif %}
        </div>
    </div>

{% endblock %}

app/posts/templates/index.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}
    <title>Новини</title>

    <div class="post-block">
        {% for pos in posts %}
        <div class="user-list-item">
            <div id="div-img-post">
                <img src="/static/posts_pics/{{ pos.image }}" width="150px">
            </div>
            <div id="div-title-post">
                <p><a href="{{ url_for('post.view_detail', pk=pos.id, id="a-href-post-list") }}">{{ pos.title }}</a></p>
            </div>
            <p class="post_description">{{ pos.description }}</p>
            <span class="post_type">
                Категорія: {{ get_category_name(pos.category_id) }}
            </span>
            <div class="post_tags">
                Теги:
                {% for tag in pos.tags %}
                    {{ tag.name }},
                {% endfor %}
            </div>
            <p class="post_tags">Створено {{ pos.created}}</p>
        </div>
        {% endfor %}
    </div>

{% endblock %}

app/posts/templates/update_post.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block content %}
    <title>Редагування</title>

    <form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div id="create-post">
        <div>
            <p>{{ render_field(form.title, id="create-post-title") }}</p>
            <p>{{ render_field(form.description, id="create-post-content") }}</p>
            <p>{{ render_field(form.image, id="create-post-picture") }}</p>
            <p>{{ render_field(form.category, id="create-post-type") }}</p>
            <p>{{ render_field(form.tags, id="create-post-type") }}</p>
            <p>{{ render_field(form.submit, value='Зберегти', id="create-post-submit_btn") }}</p>
        </div>
    </div>

</form>

{% endblock %}