app/main_bp/__init__.py
from flask import render_template, Blueprint
from flask import current_app as app
from app.getAdditionalData import *
from app.getFunction import getFooterData

main_bp = Blueprint('main_bp', __name__, template_folder="templates/main_bp")

@main_bp.route('/')
def home():
    return render_template('home.html', data=getFooterData())

@main_bp.route('/about/')
def about():
    return render_template('about.html', data=getFooterData(), skills=skills)

@main_bp.route('/myworks/')
def myworks():
    return render_template('myworks.html', data=getFooterData(), projectsData=projectsData)

@main_bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html', data=getFooterData())

app/templates/_render_field.html
{% macro render_field(field) %}
{{ field.label }}
{{ field(**kwargs)|safe }}
<ul>
{% for error in field.errors %}
    <li style="color: red">{{ error }}</li>
{% endfor %}
</ul>
{% endmacro %}

app/templates/baseTemplate.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

        {% include "header.html" %}
    </head>

    <body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>

        <div>

            {% block content %}

            {% endblock %}
        </div>

    <div class="">
        {% extends "footer.html" %}
    </div>

    </body>



</html>

app/templates/footer.html
{% block footer %}
<footer>
    <div>
        <span class="footer-span-left">Операційна система:</span>
        <span class="footer-span-right">{{data[0]}}</span>
    </div>

    <div>
        <span class="footer-span-left">Версія Python:</span>
        <span class="footer-span-right">{{data[1]}}</span>
    </div>

    <div>
        <span class="footer-span-left">User Agent:</span>
        <span class="footer-span-right">{{data[2]}}</span>
    </div>

    <div>
        <span class="footer-span-left">Поточний час:</span>
        <span class="footer-span-right">{{data[3]}}</span>
    </div>
</footer>
{% endblock %}

app/templates/header.html
{% block head %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('main_bp.home') }}" style="margin-left: -350px">
                    <img src="/static/images/mysyshyn(white).png" class="img-fluid" alt="[ mysyshyn ]" width="175" height="35">
                </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active" style="margin-left: -75px">
                            <a class="nav-link" href="{{ url_for('main_bp.home') }}">Домашня сторінка</a>
                        </li>
                        <li class="nav-item" style="margin-left: -5px">
                            <a class="nav-link" href="{{ url_for('main_bp.about') }}">Про мене</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main_bp.myworks') }}">Мої роботи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('registerzno.formRegisterDoc') }}">Форма</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.users') }}">Користувачі</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('songs.add_song') }}" style="color: white">Додати пісню</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('songs.view_songs') }}" style="color: white">Пісні</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('songs.category_crud') }}" style="color: white">Категорії пісень</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('post.index') }}">Новини</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('post.categories') }}">Категорії новин</a>
                        </li>

                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('post.create') }}">Додати новину</a>
                            </li>
                            <li class="nav-item" style="margin-right: -55px">
                                <a class="nav-link" href="{{ url_for('auth.account') }}" style="color: white">Профіль</a>
                            </li>
                            <li class="nav-item" style="margin-left: 50px">
                                <a class="nav-link" href="{{ url_for('auth.logout') }}" style="color: red" >Вихід</a>
                            </li>
                        {% else %}
                            <li class="nav-item" style="margin-left: 50px">
                                <a class="nav-link" href="{{ url_for('auth.register') }}" style="color: darkgoldenrod">Реєстрація</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.login') }}" style="color: #177199" >Вхід</a>
                            </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </header>

{% endblock %}

app/templates/registerForm.html
{% from "_render_field.html" import render_field %}

{% extends "baseTemplate.html" %}

{%block title%}
    Реєстрація документів
{% endblock %}

{%block content %}
    <title>Реєстрація документів</title>
    {% for cat, msg in get_flashed_messages(True) %}
        <div class="flash {{cat}}">{{msg}}</div>
    {% endfor %}

<div class="form-register">
    <h2 align="center">Форма реєстрації</h2>
    <hr>
    <form method="POST" action="{{ url_for('formRegisterDoc') }}">
        {{ form.csrf_token }}

        <p>{{ render_field(form.email) }}</p>
        <p>{{ render_field(form.password) }}</p>
        <p>{{ render_field(form.password_r) }}</p>

        <hr>
        <h3 align="center"><b><i>Екзаменаційний лист ЗНО магістра</i></b></h3><br>

        <p>{{ render_field(form.e_number) }}</p>
        <p>{{ render_field(form.e_pin) }}</p>
        <p>{{ render_field(form.e_year) }}</p>

        <hr>
        <h3 align="center"><b><i>Документ про освіту</i></b></h3><br>

        <p>{{ render_field(form.d_series) }}</p>
        <p>{{ render_field(form.d_number) }}</p>

        <hr>
        <br>
        <input id="input-submit-2" type="submit" value="Зареєструватись">
    </form>
</div>
{% endblock %}